dist: bionic
sudo: true
language: python

matrix:
  fast_finish: true
  include:
  - python: 3.6
    env:
    - PYTHON_VERSION="3.6"

addons:
  apt:
    packages:
    - build-essential
    - cmake
    - libboost-all-dev
    - libilmbase-dev
    - libopenexr-dev
    - tree

install:
  - wget https://github.com/OpenImageIO/oiio/archive/Release-1.8.17.tar.gz -O /tmp/OpenImageIO-1.8.17.tar.gz
  - cd /tmp
  - tar -xvf /tmp/OpenImageIO-1.8.17.tar.gz
  - cd /tmp/oiio-Release-1.8.17
  - make

script:
  - tree /tmp/oiio-Release-1.8.17/dist

deploy:
  provider: gcs
  access_key_id: GOOG1EFH2UIXKEVJMMDJHDOAK4JWCGRZ55NII2K5CP3QWPZWWT5FM5PSLDKGI
  secret_access_key:
    secure: Qu01q8+YW44WlCfB3UoMxnfkoskOzW0pHwNJ0KV40yfhjL5mVDJQWHMkDZB/VZ0bSdygRHztWHw+EeUjjdVXKOhYDYhhhuGu5LqN/pxc+unXTxgroVRL2fw53EKxS/sd/mSehs0RqXbkvTvDjcW2SGkM7DFPOAfQlnpUd2bVSFAr1laVzErz4mGNu7J5fHj+d8fkP3UGnXem96hODizDeSpyIPU2JIcDH5GXPObk5ogU/CGd5wQFe94mMcNV9GIEIqvYfsyes9GkCSJXCMmp3LNzdeh3adScA2WzuRoCWbj84ORgB8OXNAtcL4dbY308l83qAtALS+wcpE69RuafkJF6k7zvFlAzSwhFVxLL2b9WdcF5G+k6ukVF9XdSNa8BzTrICDktpw/G3Ll0uT71e958g2f6kVnmwQASya7/9e1qPrEaOvEzd+Yi5jmdY/JbYgAkkHfVXwqTMWioPdKz0ocFF24tNv3VgpXEE9uZKSFuV+ZetJ/Ud1m2avCuVEEUshsTP32J8bGI71M599H466XeclGE+Le4IMHacNHGPSCphINdm8a2CmBD8K8yLtOlrVzMYjHrDloaBUKtwd+/XtZ1gmHvB11h5PRc9uZWi9d9Qwl7ivE0S4jgnsZJWNQurKTjVn5Vls4O4qYO86OkI6rqEFobRbivRfZBpvIuJIw=
  bucket: colour-science-artifacts
  local-dir: "/tmp/oiio-Release-1.8.17/dist"
  on:
    repo: KelSolaar/TravisRamblings
