dist: bionic
sudo: true
language: python

matrix:
  fast_finish: true
  include:
  - python: 3.6
    env:
    - PYTHON_VERSION="3.6"

addons:
  apt:
    packages:
      - build-essential
      - cmake
      - libboost-all-dev
      # - libbz2-dev
      # - libgif-dev
      # - libgl1-mesa-glx
      # - libfreetype6-dev
      - libilmbase-dev
      # - libjpeg-dev
      - libopenexr-dev
      # - libpng-dev
      # - libraw-dev
      # - libtiff5-dev
      # - libwebp-dev
      # - qtbase5-dev

before_install:
  - wget https://github.com/OpenImageIO/oiio/archive/Release-1.8.17.tar.gz -O /tmp/OpenImageIO-1.8.17.tar.gz
  - tar -xvf /tmp/OpenImageIO-1.8.17.tar.gz /tmp/oiio-Release-1.8.17
  - cd /tmp/oiio-Release-1.8.17
  - make
